/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Clases.Usuario;
import graforedsocial.GrafoMatriz;
import javax.swing.JOptionPane;

/**
 *
 * @author raco1
 */
public class AñadirAmistad extends javax.swing.JFrame {
    GrafoMatriz g;
    String usuario;
    String userName;
    int cont;
    public static Modificar v2;
    
    /**
     * Creates new form AñadirAmistad
     */
    public AñadirAmistad(Modificar v2) {
        this.g=v2.graf;
        this.usuario=v2.id;
        this.userName=v2.userName;
        this.cont=0;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        imprimir.setText(g.getUsuarios().imprimir());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        userAmistad = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imprimir = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 70, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Usuarios-- Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 90, -1));
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 110, -1));
        jPanel1.add(userAmistad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        botonCrear.setText("Añadir ");
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 90, -1));

        jLabel5.setText("Tiempo de amistad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 20));

        jLabel6.setText("Nombre de amigo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 30));

        imprimir.setColumns(20);
        imprimir.setRows(5);
        jScrollPane1.setViewportView(imprimir);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 160, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(cont==0){
            JOptionPane.showMessageDialog(null,"Debe agregar al menos una relacion de amistad o el usuario no se creara");
            int sele= JOptionPane.showOptionDialog(null,"¿Desea regresar", " ", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] { "SI", "NO" }, "SI");
            if(sele==0){
                g.getUsuarios().eliminarUsuario(usuario);
                g.actualizarMatriz();
                this.dispose();
                
            }else{
                
            }
        }else{
            int sele= JOptionPane.showOptionDialog(null,"¿ Desea agregar mas amigos?", " ", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[] { "SI", "NO" }, "SI");
            if(sele==0){
                
            }else if(sele==1){
                //g.actualizarMatriz();
                cont=0;
                JOptionPane.showMessageDialog(null,"El usuario y sus relaciones de amistad se crearon con exito");
                this.dispose();
            }else{
                
            }
            
        }
        
                
                
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // TODO add your handling code here:
        Funciones func= new Funciones();
        boolean var = func.añadirAmistad(g, usuario, userAmistad.getText(), time.getText());
        if(var==true){
            cont++;
            JOptionPane.showMessageDialog(null,g.getUsuarios().buscarUser(usuario).getUserName()+" ahora es amigo de "+userAmistad.getText());
            userAmistad.setText("");
            time.setText("");
        }else{
            userAmistad.setText("");
            time.setText("");
        }

    }//GEN-LAST:event_botonCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirAmistad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirAmistad(v2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JTextArea imprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField time;
    private javax.swing.JTextField userAmistad;
    // End of variables declaration//GEN-END:variables
}
