/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Main.GrafoRedsocial;
import graforedsocial.GrafoMatriz;
import graforedsocial.Nodo;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import lectura.ArchivoTxt;
import lectura.Cargar;
import lectura.GrafoRuta;
import lectura.UsersArcos;
import mostrarGrafo.Mostrar;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.spriteManager.*;

/**
 *
 * @author AROMERO
 */
public class Main extends javax.swing.JFrame {

    GrafoMatriz grafo;
    String path;

    /**
     * Creates new form Main
     */
    public Main() {
        this.grafo = null;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        System.setProperty("org.graphstream.ui", "swing");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnShowGraph = new javax.swing.JButton();
        btnConections = new javax.swing.JButton();
        btnUploadTxt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        btnShowGraph.setText("Mostrar Grafo");
        btnShowGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGraphActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 130, -1));

        btnConections.setText("Mostrar Puentes");
        jPanel1.add(btnConections, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        btnUploadTxt.setText("Cargar txt");
        btnUploadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadTxtActionPerformed(evt);
            }
        });
        jPanel1.add(btnUploadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 100, -1));

        jButton1.setText("Mostrar islas ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        botonModificar.setText("Modificar usuarios");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(botonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 0, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Actualizar datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        if (grafo == null) {
            JOptionPane.showMessageDialog(null, "No se ha cargado informacion al grafo");
        } else {

            Modificar v2 = new Modificar(this);
            v2.setVisible(true);
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void btnUploadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadTxtActionPerformed
        // TODO add your handling code here:
        Cargar help = new Cargar();
        GrafoRuta aux = help.cargarTxt();
        grafo = aux.getG();
        grafo.generarM();
        grafo.llenarMatriz();
        path = aux.getRuta();
        JOptionPane.showMessageDialog(null, "Recuerde actualizar los datos una vez modificada la informacion");


    }//GEN-LAST:event_btnUploadTxtActionPerformed

    private void btnShowGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGraphActionPerformed
        // TODO add your handling code here:
        if (grafo == null) {
            JOptionPane.showMessageDialog(null, "No se ha cargado informacion al grafo");
        } else {
            JOptionPane.showMessageDialog(null, "Una vez se cierre la ventana del grafo se terminara el programa, si no ha guardado los cambios recomendamos no continuar");
            int sele = JOptionPane.showOptionDialog(null, "¿Desea continuar", " ", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "SI");
            if (sele == 0) {
                grafo.getUsuarios().imprimir();
                Mostrar most = new Mostrar();
                most.mostrarGrafos(grafo);
            } else {

            }

        }

    }//GEN-LAST:event_btnShowGraphActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (grafo == null) {
            JOptionPane.showMessageDialog(null, "No se ha cargado informacion al grafo");
        } else {
            ArchivoTxt escri = new ArchivoTxt();
            escri.escribirTxt(grafo.getUsuarios(), grafo.getAmigos(), path);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton btnConections;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShowGraph;
    private javax.swing.JButton btnUploadTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
